name: Despliegue Automático a InfinityFree

on:
  push:
    branches:
      - main

# Esto soluciona la advertencia de Node.js 20 obligando a usar Node 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  deploy:
    name: Subiendo archivos al hosting
    runs-on: ubuntu-latest

    steps:
    - name: 1. Obtener el código del repositorio
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Trae todo el historial para evitar el error 128 de Git

    - name: 2. Sincronizar archivos por FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: htdocs/