name: Despliegue Automático a InfinityFree

on:
  push:
    branches:
      - main # Se activa cuando subes cambios a la rama principal

jobs:
  deploy:
    name: Subiendo archivos al hosting
    runs-on: ubuntu-latest

    steps:
    - name: 1. Obtener el código del repositorio
      uses: actions/checkout@v4

    - name: 2. Sincronizar archivos por FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # InfinityFree requiere que los archivos web vayan dentro de htdocs
        server-dir: htdocs/